apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: git@github.com:SeunJim/gitops-rails-app.git
      name: rails-gitops
      type: git
      sshPrivateKeySecret:
        name: repo-secret
        key: sshPrivateKey