apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rails-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:SeunJim/gitops-rails-app.git
    targetRevision: HEAD
    path: apps/rails-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
